### ISSUE TITLE
Error pull Ensembl file from FTP

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-solr-slim#43]
This ended up being a result of parsing the ensembl version from:
https://rest.ensembl.org/info/data/?content-type=application/json
the response is
```
{
    releases: [
        0,
        108
    ]
}
```

the code that parses this expects the current release to be the first element. So it gets the release of ensembl as 0 and proceeds with that to pull data from the ensembl FTP for release 0…which doesn’t exist.

**Comment by ljwh2** [comment]
Needs code changes and deployment strategy. To be worked on after Diagram.
