### ISSUE TITLE
Solr Slim Documentation

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-solr-slim#49]
As developer
I want a Readme documentation 
For the slim solr project that describes the project features,requirements for running the project, steps to take to deploy it loclaly, how to contribute/extend the project, e.t.c

I want a Confluence documentation 
For the slim solr project that describes the deployment environements (dev, test, prod e.t.c) with clear description of how it is deloyed in each of he environments, with reference to all credentials, machines, sstorage paths e.t.c required.

**Comment by karatugo** [comment]
Please find GWAS Solr Slim docs on Confluence here. https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/GWAS+Solr+Slim+Project
